#!/opt/local/bin/ruby1.9
#
# This file was generated by RubyGems.
#
# The application 'sequel' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

gem 'sequel', version
$: << File.join(File.dirname(File.dirname($0)), "lib")
#require 'load_libs'
puts "Loading your DB ..."
require 'models'
load 'sequel'
